version: '3.8'

services:
  web:
    container_name: BuscadorGITHUB
    #restart: always
    image: php:5.6-apache
    #build: ./.docker
    ports:
      - 8080:80
    networks:
      - overlay
    volumes:
      - ./:/var/www/html/BuscadorGitHub
      - ../.docker/http/vhost_buscador.conf:/etc/apache2/sites-available/000-default.conf

networks:
  overlay:
